import { createContext, useContext, useState, useCallback } from 'react';

/**
 * RakanSewa Global i18n System
 * Supports: 'en' (English) | 'ms' (Bahasa Melayu)
 *
 * Usage in any component:
 *   const { t, lang, toggle } = useLanguage();
 *   <h1>{t('hero_headline_start')}</h1>
 */

const STRINGS = {
  en: {
    /* ── Navbar ── */
    nav_discover:      'Discover',
    nav_properties:    'Properties',
    nav_housemates:    'Matches',
    nav_preferences:   'Edit Preferences',
    nav_feedback:      'Feedback',
    nav_about:         'About',
    nav_dashboard:     'Dashboard',
    nav_admin:         'Admin',
    nav_profile:       'My Profile',
    nav_sign_in:       'Sign In',
    nav_get_started:   'Register',
    nav_sign_out:      'Sign Out',
    nav_notifications: 'Notifications',
    nav_no_notif:      'No notifications yet',
    footer_copyright:  'A platform for rental house information and housemate matching for UiTM Jasin. © 2026',

    /* ── HomePage ── */
    hero_badge:           "UiTM Jasin's Student Housing & Matching Platform",
    hero_headline_start:  'Your Perfect Housemate',
    hero_headline_accent: 'Starts Here',
    hero_sub:             'Get matched with compatible UiTM Jasin students based on budget, lifestyle, and sleep schedule. Find verified rentals, connect confidently.',
    hero_cta_housemates:  'Find Housemates',
    hero_cta_listings:    'Browse Listings',
    hero_cta_register:    'Register Free',
    hero_trust:           'UiTM-verified · Free for students · No spam',
    hero_badge_unified: "UiTM Jasin's Trusted Student Housing Hub",
    hero_headline_unified: "Find your perfect home and roomies.",
    hero_sub_unified: "Join the student community where finding a place to stay is as easy as passing your exams. Verified listings, smart matching, and zero stress.",
    hero_avatar_subtext: "Students found their home this semester",
    cta_join_now: "Join Now!",
    filter_more_filters: "More Filters",
    filter_min_price: "Min Price",
    filter_max_price: "Max Price",
    filter_all_properties: "All Properties",
    filter_landed_house: "Landed House",
    filter_apartment: "Apartment",
    filter_private_room: "Private Room",
    stat_listings:        'Active Listings',
    stat_matched:         'Students Matched',
    stat_verified:        'UiTM Verified',
    hiw_label:            'Getting Started',
    hiw_title:            'How Matching Works',
    hiw_step1_title:      'Create Your Profile',
    hiw_step1_desc:       'Sign up with your UiTM email and set your housemate preferences.',
    hiw_step2_title:      'Set Your Priorities',
    hiw_step2_desc:       'Budget, sleep pattern, lifestyle — your criteria drive the match score.',
    hiw_step3_title:      'Connect & Move In',
    hiw_step3_desc:       'Reach out to compatible housemates and secure your ideal student home.',
    feat_label:           'Platform',
    feat_title:           'Built for UiTM Students',
    feat_sub:             'Everything you need to find a safe, comfortable, and compatible living situation near campus.',
    cta_guest_title:      'Ready to find your new home?',
    cta_guest_sub:        'Join hundreds of UiTM Jasin students who found their perfect living space.',
    cta_browse:           'Browse Properties',
    cta_create_acc:       'Register Free Account',
    cta_student_listed_title:    'Find Your Matching Housemate',
    cta_student_listed_desc:     'Browse compatible students based on your set preferences and move in together.',
    cta_student_unlisted_title:  'Get Listed as a Housemate',
    cta_student_unlisted_desc:   'Complete your housemate profile so other students can find and match with you.',
    cta_browse_housemates:       'Browse Housemates',
    cta_edit_profile:            'Edit My Profile',
    cta_view_listings:           'View Listings',

    /* ── PropertiesPage ── */
    prop_title:           'Browse Properties',
    prop_subtitle:        'Verified rental listings near UiTM Jasin campus.',
    prop_filter_toggle:   'Filters',
    prop_filter_favourites: 'Favourites Only',
    prop_limit_5: 'Show: 5',
    prop_limit_10: 'Show: 10',
    prop_limit_all: 'Show: All',
    prop_recommended_budget: 'Recommended for Your Budget',
    prop_recommended_budget_sub: 'Properties closest to your preferred budget.',
    prop_recommended_badge: 'Near Your Budget',
    prop_results:         '{count} properties found',
    prop_results_filtered: 'showing filtered results',
    prop_no_results_title: 'No properties found',
    prop_no_results_sub:   'Try adjusting your filters or check back later.',
    prop_no_properties_avail: 'No properties available yet. Please check back later.',
    prop_clear_filters:   'Clear Filters',
    prop_loading:         'Loading listings…',
    prop_error_title:     'Failed to load properties',
    prop_error_sub:       'Please check your connection and try again.',
    prop_retry:           'Try Again',

    /* ── PropertyCard ── */
    card_available:       'Available',
    card_occupied:        'Occupied',
    card_per_month:       '/mo',
    card_view:            'View Details',

    /* ── PropertyFilter ── */
    filter_title:         'Filters',
    filter_clear:         'Clear All',
    filter_active:        'active',
    filter_type:          'Property Type',
    filter_room:          'Room Type',
    filter_furnish:       'Furnished Status',
    filter_price:         'Price Range (RM)',
    filter_min:           'Min',
    filter_max:           'Max',
    filter_apply:         'Apply Filters',

    /* ── PropertyDetailsPage ── */
    detail_back:          'Back to Properties',
    detail_overview:      'Overview',
    detail_about:         'About this Property',
    detail_no_desc:       'No description provided.',
    detail_amenities:     'Amenities',
    detail_contact:       'Contact Owner',
    detail_whatsapp:      'Contact via WhatsApp',
    detail_directions:    'Get Directions',
    detail_login_to_contact: 'Sign in to contact owner',
    detail_rent:          'Monthly Rent',
    detail_compatibility: 'Compatibility Score',
    detail_compat_login:  'Sign in to see your match score',
    detail_verified_trust: 'Verified Listing',
    detail_pending_approval: 'Pending Approval',

    /* ── HousematesPage ── */
    hm_title:             'Find Housemates',
    hm_subtitle:          'Browse UiTM Jasin students looking for compatible housemates.',
    hm_stats_total:       'Listed Students',
    hm_stats_great:       'Great Matches',
    hm_stats_good:        'Good Matches',
    hm_filter_all:        'All',
    hm_filter_great:      'Great Match',
    hm_filter_good:       'Good Match',
    hm_no_results:        'No housemates found matching your criteria.',
    hm_login_to_match:    'Sign in to see match scores',
    hm_why_match:         'Why you match',
    hm_match_score:       'Match Score',
    hm_budget:            'Budget',
    hm_sleep:             'Sleep',
    hm_lifestyle:         'Lifestyle',
    hm_priorities:        'Priorities',
    hm_linked_property:   'Linked Property',
    hm_filter_property:   'Filter by Linked Property:',
    hm_all_properties:    'All Properties (No Property Filter)',
    hm_clear_property_filter: 'Clear Property Filter',
    hm_filter_contact:    'Contact Availability:',
    hm_contact_all:       'All Students',
    hm_contact_shared:    'Has Contact Shared',
    hm_contact_whatsapp:  'WhatsApp Direct Only',
    hm_clear_contact_filter: 'Clear Contact Filter',
    hm_no_property:       'No property linked',
    hm_verified:          'UiTM Verified',
    hm_listed:            'Listed',

    /* ── ManageHousemateProfilePage ── */
    pref_title:           'Housemate Profile',
    pref_subtitle:        'Control how you appear in the matching system and set your compatibility criteria.',
    pref_section_visibility: 'Listing Visibility',
    pref_visibility_desc: 'Toggle this to appear on the housemate listing page.',
    pref_listed_label:    'List me as a housemate',
    pref_listed_desc:     "You'll appear in the housemate listing for others to find",
    pref_section_prefs:   'Basic Preferences',
    pref_budget:          'Monthly Budget (RM)',
    pref_sleep:           'Sleep Pattern',
    pref_lifestyle:       'Lifestyle Tags',
    pref_lifestyle_hint:  'These tags describe your lifestyle, not your matching priorities.',
    pref_section_priority: 'Compatibility Priorities',
    pref_priority_desc:   'Choose 3 things in order of importance. These drive how your match score is calculated.',
    pref_priority_1:      'Priority 1',
    pref_priority_2:      'Priority 2',
    pref_priority_3:      'Priority 3',
    pref_priority_placeholder: 'Select a priority…',
    pref_priority_error:  'Please select exactly 3 different priorities before saving.',
    pref_priority_dupe:   'Each priority must be different. Please resolve the duplicate.',
    pref_priority_ok:     'Priorities set',
    pref_section_property: 'Linked Rental Property',
    pref_property_desc:   'Link your profile to the property where you currently live or plan to stay.',
    pref_no_property:     'No linked property',
    pref_save:            'Save Changes',
    pref_discard:         'Discard Changes',
    pref_saving:          'Saving…',
    pref_saved:           'Saved! Redirecting to your profile…',
    pref_tip_title:       'Matching Tip',
    pref_live_preview: 'Live Preview',
    pref_active: 'Active',
    pref_hidden: 'Hidden',
    pref_budget_suffix: '/month budget',
    pref_linked: 'Linked',
    pref_profile_status: 'Profile Status',
    pref_verification: 'Verification',
    pref_unverified: 'Unverified',
    pref_lifestyle_select: '(select all that describe you)',
    pref_priority_others: 'Others',
    pref_priority_weight: '= {weight} of score',

    /* ── OwnerDashboard ── */
    owner_title:          'My Properties',
    owner_subtitle:       'Manage your listings and track approval status.',
    owner_new_listing:    'Create New Listing',
    owner_stat_total:     'Total Listings',
    owner_stat_approved:  'Approved',
    owner_stat_pending:   'Pending Review',
    owner_stat_rejected:  'Rejected',
    owner_no_listings_title: 'No listings yet',
    owner_no_listings_sub:   'Start by creating your first property listing.',
    owner_first_listing:  'Create First Listing',
    owner_add_listing:    'Add New Listing',
    owner_add_listing_sub: 'List your next property',
    owner_view:           'View',
    owner_edit:           'Edit',
    owner_edit_resubmit:  'Edit & Resubmit',
    owner_delete:         'Delete',
    owner_reject_reason:  'Rejection Reason',
    owner_verify_warning: 'Verification Required',
    owner_verify_desc:    'Complete your profile verification to manage property listings.',
    owner_modal_new:      'New Property Listing',
    owner_modal_edit:     'Edit Listing',
    owner_modal_resubmit: 'Edit & Resubmit',
    owner_modal_resubmit_note: 'Saving will resubmit for admin approval.',
    owner_modal_cancel:   'Cancel',
    owner_modal_submit:   'Submit for Approval',
    owner_modal_update:   'Update Listing',
    owner_modal_uploading: 'Uploading…',
    owner_approval_note:  'New properties require admin approval before going live.',
    owner_delete_title:   'Delete Property',
    owner_delete_msg:     'Are you sure you want to delete this property? This action cannot be undone.',
    owner_field_title:    'Property Title',
    owner_field_address:  'Street Address',
    owner_field_city:     'City',
    owner_field_state:    'State',
    owner_field_rent:     'Monthly Rent (RM)',
    owner_field_type:     'Property Type',
    owner_field_room:     'Room Type',
    owner_field_furnish:  'Furnished Status',
    owner_field_desc:     'Description',
    owner_field_images:   'Property Images',
    owner_images_hint:    'JPG, PNG, or WebP. Max 5MB each.',
    owner_existing_images: 'Current Images',
    owner_new_images:     'New Images to Upload',
    owner_placeholder_title: 'e.g. Cozy Room near UiTM',
    owner_placeholder_address: 'Street address',
    owner_placeholder_city: 'City',
    owner_placeholder_state: 'State',
    owner_placeholder_rent: 'e.g. 450',
    owner_placeholder_custom_amenity: 'e.g. Balcony, Swimming Pool...',
    owner_placeholder_desc: 'Describe the property — features, nearby amenities, house rules...',
    owner_field_map_title: 'Map Location (Click or Drag Marker)',
    owner_amenities_title: 'Amenities',
    owner_select_presets: 'Select Presets',
    owner_add_custom_amenities: 'Add Custom Amenities',
    owner_btn_add_amenity: '+ Add',

    /* ── Common / Shared ── */
    common_available:     'Available',
    common_occupied:      'Occupied',
    common_pending:       'Pending',
    common_approved:      'Approved',
    common_rejected:      'Rejected',
    common_verified:      'Verified',
    common_student:       'Student',
    common_owner:         'Property Owner',
    common_loading:       'Loading…',
    common_error:         'Something went wrong. Please try again.',
    common_cancel:        'Cancel',
    common_save:          'Save',
    common_edit:          'Edit',
    common_delete:        'Delete',
    common_close:         'Close',
    common_back:          'Back',
    common_per_month:     '/month',
    common_no_image:      'No image',
    common_cover:         'Cover',
    common_all:           'All',

    /* ── Homepage Feature Cards ── */
    feat_title_listings: 'Verified Listings',
    feat_desc_listings: 'Every property is reviewed and approved by our admins before going live — no surprises.',
    feat_title_distance: 'Distance from UiTM',
    feat_desc_distance: 'See exactly how far any property is from the main UiTM Jasin campus in real-time.',
    feat_title_matching: 'Smart Housemate Matching',
    feat_desc_matching: 'Get matched based on budget, sleep schedule, and lifestyle — not just availability.',
    feat_title_trust: 'Student Trust Indicators',
    feat_desc_trust: 'Verify your UiTM student identity to build credibility and connect with confidence.',

    /* ── Confirm / Rejection Modals ── */
    confirm_title: 'Are you sure?',
    confirm_desc: 'This action cannot be undone.',
    reject_title: 'Reject Property',
    reject_reason_select: 'Select a reason',
    reject_preset_image: 'Missing property image',
    reject_preset_info: 'Incomplete property information',
    reject_preset_rental: 'Invalid rental details',
    reject_preset_dupe: 'Duplicate listing',
    reject_custom: 'Other reason...',
    reject_placeholder: 'Enter your rejection reason...',
    reject_confirm: 'Confirm Rejection',

    /* ── Property Card Save Tooltips ── */
    card_tooltip_save: 'Save listing',
    card_tooltip_unsave: 'Remove from saved',

    /* ── Owner Dashboard Additions ── */
    owner_no_photo: 'No photo',
    owner_listings_total: '{count} total',

    /* ── Admin Dashboard ── */
    admin_title: 'Admin Dashboard',
    admin_subtitle: 'System overview, property approvals, and user management.',
    admin_stat_users: 'Total Users',
    admin_stat_listings: 'Total Listings',
    admin_stat_pending: 'Pending Approvals',
    admin_stat_feedback: 'Unresolved Feedback',
    admin_tab_listings: 'Property Listings',
    admin_tab_users: 'User Management',
    admin_tab_feedback: 'User Feedback',
    admin_table_property: 'Property',
    admin_table_location: 'Location',
    admin_table_type: 'Type',
    admin_table_rent: 'Rent',
    admin_table_actions: 'Actions',
    admin_table_status: 'Status',
    admin_table_reason: 'Rejection Reason',
    admin_table_name: 'Name',
    admin_table_email: 'Email',
    admin_table_role: 'Role',
    admin_all_listings: 'All Listings',
    admin_all_users: 'All Users',
    admin_caught_up: 'All caught up! No pending approvals.',
    admin_no_feedback: 'No feedback submitted yet.',
    admin_action_approve: 'Approve',
    admin_action_reject: 'Reject',
    admin_action_resolve: 'Mark Resolved',

    /* ── About Page ── */
    about_title: 'About RakanSewa',
    about_subtitle: 'A dedicated platform helping UiTM Jasin students find reliable housing and compatible housemates.',
    about_proj_info: 'Project Information',
    about_proj_name: 'Project Name',
    about_proj_name_val: 'RakanSewa: Housemate Matching and Rental House Information Finder System',
    about_dev: 'Developer',
    about_univ: 'University',
    about_univ_val: 'Universiti Teknologi MARA (UiTM) Cawangan Melaka, Kampus Jasin',
    about_platform: 'Platform',
    about_platform_val: 'Web-Based System (React + Spring Boot)',
    about_prob_sol: 'Problem & Solution',
    about_prob_title: 'The Problem',
    about_prob_desc: 'Finding secure off-campus accommodation and compatible housemates is often a stressful process for university students. Many face issues such as unverified listings, scam landlords, and mismatched housemates with conflicting lifestyles.',
    about_sol_title: 'The Solution',
    about_sol_desc: 'RakanSewa provides a centralized, secure platform exclusively designed for UiTM students. It addresses these challenges through landlord verification, student identity trust badges, and an intelligent housemate compatibility system based on budget and lifestyle preferences.',
    about_key_features: 'Key Features',
    about_feat_verification: 'UiTM Student Verification',
    about_feat_listing: 'Property Listing & Approval',
    about_feat_matching: 'Housemate Matching System',
    about_feat_admin: 'Admin Approval Workflow',
    about_feat_feedback: 'User Feedback System',
    about_tech_stack: 'Technology Stack',
    about_academic_proj: 'Academic Project',
    about_academic_desc: 'This system is developed as part of an undergraduate final year project at UiTM Cawangan Melaka, Kampus Jasin.',

    /* ── Login Page ── */
    login_welcome: 'Welcome back',
    login_sub: 'Sign in to your RakanSewa account.',
    login_email: 'Email',
    login_email_placeholder: 'your@email.com',
    login_password: 'Password',
    login_forgot_password: 'Forgot password?',
    login_password_placeholder: 'Enter your password',
    login_btn_signin: 'Sign In',
    login_btn_signing_in: 'Signing in…',
    login_or: 'or',
    login_google: 'Continue with Google',
    login_no_account: "Don't have an account?",
    login_register_free: 'Register free →',
    login_uitm_platform: 'UiTM Jasin Platform',
    login_hero_title: 'Find your perfect home',
    login_hero_subtitle: 'and compatible housemates.',
    login_hero_desc: 'The trusted platform for UiTM Jasin students to discover verified rental listings and compatible roommates.',
    login_feat_listings: 'UiTM student-verified listings',
    login_feat_matching: 'Smart housemate compatibility score',
    login_feat_location: 'Properties near UiTM Jasin campus',
    login_hero_footer: 'Free for all UiTM Jasin students & verified landlords.',
    login_success_registered: 'Registration successful! Sign in and complete your UiTM student verification in your profile.',
    login_error_invalid: 'Invalid email or password. Please try again.',
    login_error_google: 'Failed to sign in with Google. Please try again.',
    login_error_google_failed: 'Google Sign-In failed. Please try again.',
    login_hide_pwd: 'Hide password',
    login_show_pwd: 'Show password',

    /* ── Register Page ── */
    reg_title: 'Register your account',
    reg_sub: 'Join RakanSewa and start finding your perfect place.',
    reg_fullname: 'Full Name',
    reg_fullname_placeholder: 'Enter your full name',
    reg_email: 'Email',
    reg_email_placeholder: 'your@email.com',
    reg_email_detected: 'UiTM student email detected — auto-verification will apply!',
    reg_password: 'Password',
    reg_password_placeholder: 'Create a strong password',
    reg_iam: 'I am a…',
    reg_role_student: 'UiTM Student',
    reg_role_owner: 'Property Owner',
    reg_verification_title: 'UiTM Student Verification',
    reg_matric: 'Matric Number',
    reg_matric_placeholder: 'e.g. 2022456146',
    reg_uitm_email: 'UiTM Student Email',
    reg_uitm_email_placeholder: '2022456146@student.uitm.edu.my',
    reg_warning_mismatch: 'Matric number must match your UiTM student email.',
    reg_warning_match: 'Matric number matches UiTM email — auto-verification will apply!',
    reg_btn_create: 'Register Account',
    reg_btn_creating: 'Registering Account…',
    reg_free_account: 'Free Student Account',
    reg_hero_title: 'Join the UiTM Jasin',
    reg_hero_subtitle: 'student community.',
    reg_hero_desc: 'Register your free account today. Browse verified listings, find compatible housemates, and secure your ideal home near campus.',
    reg_feat_listings: 'Browse verified property listings',
    reg_feat_matching: 'Match with compatible housemates',
    reg_feat_safety: 'Safe, student-only community',
    reg_already_have_account: 'Already have an account?',
    reg_signin_link: 'Sign in here',

    /* ── ForgotPassword Page ── */
    forgot_left_title_1: 'Recover your account',
    forgot_left_title_2: 'securely.',
    forgot_left_desc: 'Enter the email address associated with your RakanSewa account. We will send you a secure link to reset your password.',
    forgot_left_priority: 'Your account security is our priority. Reset links expire after 30 minutes.',
    forgot_title: 'Forgot Password',
    forgot_sub: 'Enter your email and we\'ll send you a reset link.',
    forgot_success: 'If an account with that email exists, a password reset link has been sent. Please check your inbox (and spam folder).',
    forgot_back: 'Back to Login',
    forgot_email: 'Email Address',
    forgot_email_placeholder: 'Enter your registered email',
    forgot_sending: 'Sending...',
    forgot_send_btn: 'Send Reset Link',
    forgot_remember: 'Remember your password?',
    forgot_signin_link: 'Sign in',

    /* ── ResetPassword Page ── */
    reset_left_title_1: 'Set a new password',
    reset_left_title_2: 'for your account.',
    reset_left_desc: 'Choose a strong password to keep your RakanSewa account secure. Your password should be at least 6 characters long.',
    reset_left_priority: 'Use a unique password you don\'t use on other websites.',
    reset_invalid_title: 'Invalid Reset Link',
    reset_invalid_desc: 'This password reset link is missing or invalid. Please request a new reset link.',
    reset_request_new: 'Request New Link',
    reset_title: 'Reset Password',
    reset_sub: 'Enter your new password below.',
    reset_success: 'Your password has been reset successfully!',
    reset_new_label: 'New Password',
    reset_confirm_label: 'Confirm Password',
    reset_new_placeholder: 'At least 6 characters',
    reset_confirm_placeholder: 'Re-enter your password',
    reset_mismatch: 'Passwords do not match.',
    reset_match: 'Passwords match.',
    reset_btn: 'Reset Password',
    reset_btn_resetting: 'Resetting...',
    reset_back: 'Back to Login',
    reset_error_len: 'Password must be at least 6 characters.',

    /* ── Feedback Page ── */
    fb_not_logged_title: 'Please Login',
    fb_not_logged_desc: 'You must be logged in to submit feedback.',
    fb_not_logged_btn: 'Login',
    fb_title: 'Submit Feedback',
    fb_guide_title: 'Feedback Guide',
    fb_subtitle: 'Help us improve RakanSewa by sharing your thoughts, suggestions, or reports.',
    fb_why_title: 'Why Feedback Matters',
    fb_why_desc: 'Your feedback directly shapes the development of RakanSewa. Every suggestion and report is reviewed by the admin team and considered for future improvements.',
    fb_categories_title: 'Feedback Categories',
    fb_cat_comment: 'Comment',
    fb_cat_comment_desc: 'General thoughts or observations about the platform.',
    fb_cat_suggestion: 'Suggestion',
    fb_cat_suggestion_desc: 'Ideas for new features or improvements.',
    fb_cat_report: 'Report',
    fb_cat_report_desc: 'Report a bug, issue, or policy violation.',
    fb_logged_in_as: 'Logged in as',
    fb_form_title: 'Your Feedback',
    fb_success: 'Thank you! Your feedback has been submitted successfully.',
    fb_error: 'Failed to submit feedback. Please try again.',
    fb_label_category: 'Category',
    fb_label_subject: 'Subject',
    fb_placeholder_subject: 'Brief summary of your feedback',
    fb_label_message: 'Message',
    fb_placeholder_message: 'Type your feedback message here...',
    fb_btn_submit: 'Submit Feedback',
    fb_btn_submitting: 'Submitting...',
    fb_ready_title: 'Ready to Share Feedback?',
    fb_ready_desc: 'Help other students by sharing your house reviews and experiences on RakanSewa.',
    fb_btn_write: 'Write Feedback',
    fb_community_title: 'Community Feedback',
    fb_stat_total: 'Total Feedback',
    fb_stat_comments: 'Comments',
    fb_stat_suggestions: 'Suggestions',
    fb_stat_reports: 'Reports',
    fb_filter_all: 'All Feedbacks',
    fb_no_feedback: 'No feedback found for this category.',
    fb_history_title: 'My Feedback History',
    fb_no_history: "You haven't submitted any feedback yet.",
    fb_tbl_category: 'Category',
    fb_tbl_subject: 'Subject',
    fb_tbl_date: 'Date',
    fb_tbl_status: 'Status',
    fb_status_pending: 'Pending',
    fb_status_reviewed: 'Reviewed',
    fb_status_implemented: 'Implemented',
    fb_anon_student: 'Anonymous Student',
    fb_btn_cancel: 'Cancel',
    fb_btn_done: 'Done',

    /* ── Profile Page ── */
    profile_google_success: 'Google account created successfully!',
    profile_google_success_sub: 'Please complete your profile — add your phone number, matric number, and lifestyle preferences.',
    profile_not_verified: 'Not Verified — Complete UiTM Student Verification',
    profile_not_verified_sub: 'Your matric number must match your UiTM student email, e.g. 2022456146@student.uitm.edu.my.',
    profile_not_verified_hint: 'Fill in your matric number and UiTM email in your profile to get verified automatically.',
    profile_saved: 'Profile saved successfully!',
    profile_role_housemate: 'Housemate',
    profile_role_verified_student: 'Verified Student',
    profile_role_not_verified: 'Not Verified',
    profile_acc_info: 'Account Information',
    profile_btn_edit: 'Edit Profile',
    profile_btn_cancel: 'Cancel',
    profile_btn_save: 'Save Changes',
    profile_btn_saving: 'Saving...',
    profile_label_fullname: 'Full Name',
    profile_label_email: 'Email Address',
    profile_label_phone: 'Phone Number',
    profile_label_phone_placeholder: 'e.g. 0123456789',
    profile_label_matric: 'Matric Number',
    profile_label_matric_placeholder: 'e.g. 2022456146',
    profile_label_uitm_email: 'UiTM Email',
    profile_label_uitm_email_placeholder: 'e.g. 2022456146@student.uitm.edu.my',
    profile_uitm_email_hint: 'Must match your matric number, e.g. 2022456146@student.uitm.edu.my',
    profile_not_provided: 'Not provided',
    profile_acc_role: 'Account Role',
    profile_housemate_profile: 'Housemate Profile',
    profile_btn_manage_housemate: 'Edit Housemate Profile',
    profile_status_visible: 'Listed & Visible',
    profile_label_budget: 'Monthly Budget',
    profile_label_sleep: 'Sleep Schedule',
    profile_label_lifestyles: 'Total Lifestyles',
    profile_lifestyles_tags: '{count} tag(s)',
    profile_label_lifestyle_tags_section: 'Lifestyle Tags',
    profile_label_priorities_section: 'Matching Priorities',
    profile_not_listed: 'Not listed as a housemate',
    profile_not_listed_desc: 'Your profile is currently hidden from housemate searches.',
    profile_property_summary: 'Property Summary',
    profile_btn_manage_properties: 'Manage Properties',
    profile_total: 'Total',
    profile_approved: 'Approved',
    profile_pending: 'Pending',
    profile_rejected: 'Rejected',
    profile_no_listings_yet: 'No listings yet. Go to Manage Properties to add your first property.',
    profile_system_summary: 'System Summary',
    profile_btn_open_admin: 'Open Admin Dashboard',
    profile_admin_prop_approvals: 'Property Approvals',
    profile_admin_prop_approvals_sub: 'Review pending listings',
    profile_admin_user_mgmt: 'User Management',
    profile_admin_user_mgmt_sub: 'View all registered users',
    profile_admin_feedback: 'User Feedback',
    profile_admin_feedback_sub: 'Manage reports & suggestions',
    profile_admin_total_users: 'Total Users',
    profile_admin_students: 'Students',
    profile_admin_owners: 'Owners',
    profile_admin_total_listings: 'Total Listings',
    profile_admin_pending_approvals: 'Pending Approvals',
    profile_admin_processed: 'Processed',
    profile_linked_property: 'Linked Rental Property',
    profile_no_property_linked: 'No property linked currently',

    /* ── Property Filter Component ── */
    pfilter_search: 'Search',
    pfilter_search_placeholder: 'Title or city...',
    pfilter_furnishing: 'Furnishing',

    /* ── Dynamic options mapping ── */
    'Budget': 'Budget',
    'Sleep Pattern': 'Sleep Pattern',
    'Cleanliness': 'Cleanliness',
    'Quietness': 'Quietness',
    'Social Style': 'Social Style',
    'Study Habit': 'Study Habit',
    'Activity Level': 'Activity Level',
    'Flexibility': 'Flexibility',
    'Clean': 'Clean',
    'Quiet': 'Quiet',
    'Social': 'Social',
    'Studious': 'Studious',
    'Active': 'Active',
    'Flexible': 'Flexible',
    'Early Bird': 'Early Bird',
    'Night Owl': 'Night Owl',
    'Monthly rent affordability': 'Monthly rent affordability',
    'Early bird or night owl': 'Early bird or night owl',
    'Tidiness & hygiene habits': 'Tidiness & hygiene habits',
    'Noise level preference': 'Noise level preference',
    'Social or introverted': 'Social or introverted',
    'Study environment needs': 'Study environment needs',
    'Active lifestyle match': 'Active lifestyle match',
    'Adaptability to schedules': 'Adaptability to schedules',
    'Honest preferences lead to better matches.': 'Honest preferences lead to better matches.',
    'Setting a realistic budget improves compatibility.': 'Setting a realistic budget improves compatibility.',
    'Sleep schedule is the #1 source of housemate conflict.': 'Sleep schedule is the #1 source of housemate conflict.',
    'More lifestyle tags = more precise matching.': 'More lifestyle tags = more precise matching.',
    'Linked property helps others find you faster.': 'Linked property helps others find you faster.',
    'Apartment': 'Apartment',
    'Terrace': 'Terrace',
    'Condo': 'Condo',
    'Single': 'Single',
    'Master': 'Master',
    'Middle': 'Middle',
    'Fully Furnished': 'Fully Furnished',
    'Partially Furnished': 'Partially Furnished',
    'Unfurnished': 'Unfurnished',
    'Melaka': 'Melaka',
    'filter_location': 'Location',
    'filter_all_locations': 'All Locations',
    'filter_all_types': 'All Types',
    unsaved_title: 'Unsaved Changes',
    unsaved_msg: 'You have unsaved changes. Do you want to save before leaving?',
    unsaved_save: 'Save Changes',
    unsaved_discard: 'Discard',
    unsaved_cancel: 'Cancel',
    val_err_required: 'This field is required.',
    val_err_email_invalid: 'Please enter a valid email address.',
    val_err_phone_numeric: 'Phone number must contain only numbers.',
    val_err_phone_empty: 'Phone number cannot be empty.',
    val_err_too_long: 'This field exceeds the maximum limit of {max} characters.',
    val_err_numeric_positive: 'Must be a positive number greater than 0.',
    val_err_numeric_only: 'Must be a number.',
    val_err_select_empty: 'Please select a valid option.',
    val_err_password_len: 'Password must be at least 6 characters.',
    val_err_max_value: 'Maximum value allowed is {max}.',
    profile_label_allow_contact: 'Allow contact sharing',
    profile_label_show_whatsapp: 'Show WhatsApp button',
    profile_allow_contact_hint: 'If enabled, matched students will see a button to contact you.',
    profile_show_whatsapp_hint: 'Enable direct messaging via WhatsApp link.',
    profile_label_contact_settings: 'Contact Privacy Settings',
    match_contact_student: 'Contact Student',
    match_contact_disabled: 'Contact Not Shared',
    match_whatsapp_intro: 'Hi! I found your profile on RakanSewa. Can we be housemates?',
  },

  ms: {
    /* ── Navbar ── */
    nav_discover:      'Temui',
    nav_properties:    'Hartanah',
    nav_housemates:    'Padanan',
    nav_preferences:   'Edit Keutamaan',
    nav_feedback:      'Maklum Balas',
    nav_about:         'Tentang',
    nav_dashboard:     'Papan Pemuka',
    nav_admin:         'Pentadbir',
    nav_profile:       'Profil Saya',
    nav_sign_in:       'Log Masuk',
    nav_get_started:   'Daftar',
    nav_sign_out:      'Log Keluar',
    nav_notifications: 'Pemberitahuan',
    nav_no_notif:      'Tiada pemberitahuan',
    footer_copyright:  'Platform maklumat rumah sewa dan padanan rakan serumah untuk UiTM Jasin. © 2026',

    /* ── HomePage ── */
    hero_badge:           'Platform Perumahan Pelajar UiTM Jasin',
    hero_headline_start:  'Rakan Serumah Terbaik',
    hero_headline_accent: 'Bermula Di Sini',
    hero_sub:             'Dapatkan padanan dengan pelajar UiTM Jasin berdasarkan bajet, gaya hidup, dan jadual tidur. Cari sewa yang disahkan, hubungi dengan yakin.',
    hero_cta_housemates:  'Cari Rakan Serumah',
    hero_cta_listings:    'Semak Senarai',
    hero_cta_register:    'Daftar Percuma',
    hero_trust:           'Disahkan UiTM · Percuma untuk pelajar · Tiada spam',
    hero_badge_unified: "Hab Perumahan Pelajar Dipercayai UiTM Jasin",
    hero_headline_unified: "Cari rumah dan rakan serumah ideal anda.",
    hero_sub_unified: "Sertai komuniti pelajar di mana mencari tempat tinggal semudah lulus peperiksaan anda. Senarai disahkan, padanan bijak, dan sifar stres.",
    hero_avatar_subtext: "Pelajar menemui rumah mereka semester ini",
    cta_join_now: "Sertai Sekarang!",
    filter_more_filters: "Lebih Banyak Penapis",
    filter_min_price: "Harga Min",
    filter_max_price: "Harga Maks",
    filter_all_properties: "Semua Hartanah",
    filter_landed_house: "Rumah Teres",
    filter_apartment: "Apartmen",
    filter_private_room: "Bilik Peribadi",
    stat_listings:        'Senarai Aktif',
    stat_matched:         'Pelajar Dipadankan',
    stat_verified:        'Disahkan UiTM',
    hiw_label:            'Cara Bermula',
    hiw_title:            'Cara Padanan Berfungsi',
    hiw_step1_title:      'Buat Profil Anda',
    hiw_step1_desc:       'Daftar dengan e-mel UiTM anda dan tetapkan pilihan rakan serumah.',
    hiw_step2_title:      'Tetapkan Keutamaan',
    hiw_step2_desc:       'Bajet, jadual tidur, gaya hidup — kriteria anda menentukan skor padanan.',
    hiw_step3_title:      'Hubungi & Pindah Masuk',
    hiw_step3_desc:       'Hubungi rakan serumah yang serasi dan amankan rumah pelajar ideal anda.',
    feat_label:           'Platform',
    feat_title:           'Dibina Untuk Pelajar UiTM',
    feat_sub:             'Semua yang anda perlukan untuk mencari tempat tinggal yang selamat, selesa, dan serasi berhampiran kampus.',
    cta_guest_title:      'Bersedia mencari rumah baru?',
    cta_guest_sub:        'Sertai ratusan pelajar UiTM Jasin yang telah mendapat tempat tinggal sempurna mereka.',
    cta_browse:           'Semak Hartanah',
    cta_create_acc:       'Daftar Akaun Percuma',
    cta_student_listed_title:    'Cari Rakan Serumah Anda',
    cta_student_listed_desc:     'Semak pelajar yang serasi berdasarkan keutamaan anda dan pindah bersama.',
    cta_student_unlisted_title:  'Sertai Sebagai Rakan Serumah',
    cta_student_unlisted_desc:   'Lengkapkan profil anda supaya pelajar lain dapat mencari dan memadankan anda.',
    cta_browse_housemates:       'Semak Rakan Serumah',
    cta_edit_profile:            'Edit Profil Saya',
    cta_view_listings:           'Lihat Senarai',

    /* ── PropertiesPage ── */
    prop_title:           'Semak Hartanah',
    prop_subtitle:        'Senarai sewa yang disahkan berhampiran kampus UiTM Jasin.',
    prop_filter_toggle:   'Tapis',
    prop_filter_favourites: 'Kegemaran Sahaja',
    prop_limit_5: 'Papar: 5',
    prop_limit_10: 'Papar: 10',
    prop_limit_all: 'Papar: Semua',
    prop_recommended_budget: 'Disyorkan untuk Bajet Anda',
    prop_recommended_budget_sub: 'Hartanah yang paling dekat dengan bajet pilihan anda.',
    prop_recommended_badge: 'Dekat Bajet Anda',
    prop_results:         '{count} hartanah dijumpai',
    prop_results_filtered: 'menunjukkan hasil tapisan',
    prop_no_results_title: 'Tiada hartanah dijumpai',
    prop_no_results_sub:   'Cuba laraskan penapis anda atau semak semula kemudian.',
    prop_no_properties_avail: 'Tiada hartanah yang tersedia lagi. Sila semak semula kemudian.',
    prop_clear_filters:   'Padam Penapis',
    prop_loading:         'Memuatkan senarai…',
    prop_error_title:     'Gagal memuatkan hartanah',
    prop_error_sub:       'Sila semak sambungan anda dan cuba lagi.',
    prop_retry:           'Cuba Lagi',

    /* ── PropertyCard ── */
    card_available:       'Tersedia',
    card_occupied:        'Diduduki',
    card_per_month:       '/bln',
    card_view:            'Lihat Butiran',

    /* ── PropertyFilter ── */
    filter_title:         'Penapis',
    filter_clear:         'Padam Semua',
    filter_active:        'aktif',
    filter_type:          'Jenis Hartanah',
    filter_room:          'Jenis Bilik',
    filter_furnish:       'Status Perabot',
    filter_price:         'Julat Harga (RM)',
    filter_min:           'Min',
    filter_max:           'Maks',
    filter_apply:         'Guna Penapis',

    /* ── PropertyDetailsPage ── */
    detail_back:          'Kembali ke Hartanah',
    detail_overview:      'Gambaran Keseluruhan',
    detail_about:         'Tentang Hartanah Ini',
    detail_no_desc:       'Tiada keterangan diberikan.',
    detail_amenities:     'Kemudahan',
    detail_contact:       'Hubungi Pemilik',
    detail_whatsapp:      'Hubungi via WhatsApp',
    detail_directions:    'Dapatkan Arah',
    detail_login_to_contact: 'Log masuk untuk hubungi pemilik',
    detail_rent:          'Sewa Bulanan',
    detail_compatibility: 'Skor Keserasian',
    detail_compat_login:  'Log masuk untuk lihat skor padanan anda',
    detail_verified_trust: 'Senarai Disahkan',
    detail_pending_approval: 'Menunggu Kelulusan',

    /* ── HousematesPage ── */
    hm_title:             'Cari Rakan Serumah',
    hm_subtitle:          'Semak pelajar UiTM Jasin yang mencari rakan serumah serasi.',
    hm_stats_total:       'Pelajar Tersenarai',
    hm_stats_great:       'Padanan Terbaik',
    hm_stats_good:        'Padanan Baik',
    hm_filter_all:        'Semua',
    hm_filter_great:      'Padanan Terbaik',
    hm_filter_good:       'Padanan Baik',
    hm_no_results:        'Tiada rakan serumah dijumpai mengikut kriteria anda.',
    hm_login_to_match:    'Log masuk untuk lihat skor padanan',
    hm_why_match:         'Sebab padanan anda',
    hm_match_score:       'Skor Padanan',
    hm_budget:            'Bajet',
    hm_sleep:             'Jadual Tidur',
    hm_lifestyle:         'Gaya Hidup',
    hm_priorities:        'Keutamaan',
    hm_linked_property:   'Hartanah Berkaitan',
    hm_filter_property:   'Tapis mengikut Kediaman Berkaitan:',
    hm_all_properties:    'Semua Kediaman (Tanpa Penapis)',
    hm_clear_property_filter: 'Kosongkan Penapis Kediaman',
    hm_filter_contact:    'Ketersediaan Hubungan:',
    hm_contact_all:       'Semua Pelajar',
    hm_contact_shared:    'Ada Maklumat Hubungan',
    hm_contact_whatsapp:  'WhatsApp Sahaja',
    hm_clear_contact_filter: 'Kosongkan Penapis Hubungan',
    hm_no_property:       'Tiada hartanah berkaitan',
    hm_verified:          'Disahkan UiTM',
    hm_listed:            'Tersenarai',

    /* ── ManageHousemateProfilePage ── */
    pref_title:           'Profil Rakan Serumah',
    pref_subtitle:        'Kawal bagaimana anda muncul dalam sistem padanan dan tetapkan kriteria keserasian anda.',
    pref_section_visibility: 'Keterlihatan Senarai',
    pref_visibility_desc: 'Togol ini untuk muncul di halaman senarai rakan serumah.',
    pref_listed_label:    'Senaraikan saya sebagai rakan serumah',
    pref_listed_desc:     'Anda akan muncul dalam senarai rakan serumah untuk orang lain jumpa',
    pref_section_prefs:   'Pilihan Asas',
    pref_budget:          'Bajet Bulanan (RM)',
    pref_sleep:           'Corak Tidur',
    pref_lifestyle:       'Tag Gaya Hidup',
    pref_lifestyle_hint:  'Tag ini menggambarkan gaya hidup anda, bukan keutamaan padanan.',
    pref_section_priority: 'Keutamaan Keserasian',
    pref_priority_desc:   'Pilih 3 perkara mengikut urutan kepentingan. Ini menentukan cara skor padanan anda dikira.',
    pref_priority_1:      'Keutamaan 1',
    pref_priority_2:      'Keutamaan 2',
    pref_priority_3:      'Keutamaan 3',
    pref_priority_placeholder: 'Pilih keutamaan…',
    pref_priority_error:  'Sila pilih tepat 3 keutamaan yang berbeza sebelum menyimpan.',
    pref_priority_dupe:   'Setiap keutamaan mesti berbeza. Sila selesaikan pendua.',
    pref_priority_ok:     'Keutamaan ditetapkan',
    pref_section_property: 'Hartanah Sewa Berkaitan',
    pref_property_desc:   'Kaitkan profil anda dengan hartanah di mana anda kini tinggal atau bercadang untuk menginap.',
    pref_no_property:     'Tiada hartanah berkaitan',
    pref_save:            'Simpan Perubahan',
    pref_discard:         'Buang Perubahan',
    pref_saving:          'Menyimpan…',
    pref_saved:           'Disimpan! Mengarahkan ke profil anda…',
    pref_tip_title:       'Petua Padanan',
    pref_live_preview: 'Pratinjau Langsung',
    pref_active: 'Aktif',
    pref_hidden: 'Tersembunyi',
    pref_budget_suffix: '/bajet sebulan',
    pref_linked: 'Berkaitan',
    pref_profile_status: 'Status Profil',
    pref_verification: 'Pengesahan',
    pref_unverified: 'Belum Disahkan',
    pref_lifestyle_select: '(pilih semua yang menggambarkan anda)',
    pref_priority_others: 'Lain-lain',
    pref_priority_weight: '= {weight} daripada skor',

    /* ── OwnerDashboard ── */
    owner_title:          'Hartanah Saya',
    owner_subtitle:       'Urus senarai anda dan pantau status kelulusan.',
    owner_new_listing:    'Cipta Senarai Baru',
    owner_stat_total:     'Jumlah Senarai',
    owner_stat_approved:  'Diluluskan',
    owner_stat_pending:   'Menunggu Semakan',
    owner_stat_rejected:  'Ditolak',
    owner_no_listings_title: 'Tiada senarai lagi',
    owner_no_listings_sub:   'Mulakan dengan mencipta senarai hartanah pertama anda.',
    owner_first_listing:  'Cipta Senarai Pertama',
    owner_add_listing:    'Tambah Senarai Baru',
    owner_add_listing_sub: 'Senaraikan hartanah seterusnya',
    owner_view:           'Lihat',
    owner_edit:           'Edit',
    owner_edit_resubmit:  'Edit & Hantar Semula',
    owner_delete:         'Padam',
    owner_reject_reason:  'Sebab Penolakan',
    owner_verify_warning: 'Pengesahan Diperlukan',
    owner_verify_desc:    'Lengkapkan pengesahan profil anda untuk mengurus senarai hartanah.',
    owner_modal_new:      'Senarai Hartanah Baru',
    owner_modal_edit:     'Edit Senarai',
    owner_modal_resubmit: 'Edit & Hantar Semula',
    owner_modal_resubmit_note: 'Menyimpan akan menghantar semula untuk kelulusan pentadbir.',
    owner_modal_cancel:   'Batal',
    owner_modal_submit:   'Hantar untuk Kelulusan',
    owner_modal_update:   'Kemaskini Senarai',
    owner_modal_uploading: 'Memuat naik…',
    owner_approval_note:  'Hartanah baru memerlukan kelulusan pentadbir sebelum disiarkan.',
    owner_delete_title:   'Padam Hartanah',
    owner_delete_msg:     'Adakah anda pasti ingin memadamkan hartanah ini? Tindakan ini tidak boleh dibatalkan.',
    owner_field_title:    'Tajuk Hartanah',
    owner_field_address:  'Alamat Jalan',
    owner_field_city:     'Bandar',
    owner_field_state:    'Negeri',
    owner_field_rent:     'Sewa Bulanan (RM)',
    owner_field_type:     'Jenis Hartanah',
    owner_field_room:     'Jenis Bilik',
    owner_field_furnish:  'Status Perabot',
    owner_field_desc:     'Keterangan',
    owner_field_images:   'Gambar Hartanah',
    owner_images_hint:    'JPG, PNG, atau WebP. Maks 5MB setiap satu.',
    owner_existing_images: 'Gambar Semasa',
    owner_new_images:     'Gambar Baru untuk Dimuat Naik',
    owner_placeholder_title: 'cth. Bilik Selesa berhampiran UiTM',
    owner_placeholder_address: 'Alamat jalan',
    owner_placeholder_city: 'Bandar',
    owner_placeholder_state: 'Negeri',
    owner_placeholder_rent: 'cth. 450',
    owner_placeholder_custom_amenity: 'cth. Balkoni, Kolam Renang...',
    owner_placeholder_desc: 'Terangkan hartanah — kemudahan, kemudahan berhampiran, peraturan rumah...',
    owner_field_map_title: 'Lokasi Peta (Klik atau Seret Penanda)',
    owner_amenities_title: 'Kemudahan',
    owner_select_presets: 'Pilih Praset',
    owner_add_custom_amenities: 'Tambah Kemudahan Kustom',
    owner_btn_add_amenity: '+ Tambah',

    /* ── Common / Shared ── */
    common_available:     'Tersedia',
    common_occupied:      'Diduduki',
    common_pending:       'Menunggu',
    common_approved:      'Diluluskan',
    common_rejected:      'Ditolak',
    common_verified:      'Disahkan',
    common_student:       'Pelajar',
    common_owner:         'Tuan Rumah',
    common_loading:       'Memuatkan…',
    common_error:         'Sesuatu telah berlaku. Sila cuba lagi.',
    common_cancel:        'Batal',
    common_save:          'Simpan',
    common_edit:          'Edit',
    common_delete:        'Padam',
    common_close:         'Tutup',
    common_back:          'Kembali',
    common_per_month:     '/bulan',
    common_no_image:      'Tiada gambar',
    common_cover:         'Tutupan',
    common_all:           'Semua',

    /* ── Homepage Feature Cards ── */
    feat_title_listings: 'Senarai Terverifikasi',
    feat_desc_listings: 'Setiap hartanah disemak dan diluluskan oleh pentadbir kami sebelum disiarkan — tiada kejutan.',
    feat_title_distance: 'Jarak dari UiTM',
    feat_desc_distance: 'Lihat dengan tepat sejauh mana jarak mana-mana hartanah dari kampus utama UiTM Jasin secara masa nyata.',
    feat_title_matching: 'Padanan Rakan Serumah Pintar',
    feat_desc_matching: 'Dapatkan padanan berdasarkan bajet, jadual tidur, dan gaya hidup — bukan hanya ketersediaan.',
    feat_title_trust: 'Penunjuk Kepercayaan Pelajar',
    feat_desc_trust: 'Sahkan identiti pelajar UiTM anda untuk membina kredibiliti dan berhubung dengan yakin.',

    /* ── Confirm / Rejection Modals ── */
    confirm_title: 'Adakah anda pasti?',
    confirm_desc: 'Tindakan ini tidak boleh dibatalkan.',
    reject_title: 'Tolak Hartanah',
    reject_reason_select: 'Pilih sebab',
    reject_preset_image: 'Gambar hartanah tiada',
    reject_preset_info: 'Maklumat hartanah tidak lengkap',
    reject_preset_rental: 'Butiran sewaan tidak sah',
    reject_preset_dupe: 'Senarai bertindih',
    reject_custom: 'Sebab lain...',
    reject_placeholder: 'Masukkan sebab penolakan anda...',
    reject_confirm: 'Sahkan Penolakan',

    /* ── Property Card Save Tooltips ── */
    card_tooltip_save: 'Simpan senarai',
    card_tooltip_unsave: 'Buang dari simpanan',

    /* ── Owner Dashboard Additions ── */
    owner_no_photo: 'Tiada gambar',
    owner_listings_total: 'Jumlah {count}',

    /* ── Admin Dashboard ── */
    admin_title: 'Papan Pemuka Pentadbir',
    admin_subtitle: 'Gambaran keseluruhan sistem, kelulusan hartanah, dan pengurusan pengguna.',
    admin_stat_users: 'Jumlah Pengguna',
    admin_stat_listings: 'Jumlah Senarai',
    admin_stat_pending: 'Menunggu Kelulusan',
    admin_stat_feedback: 'Maklum Balas Belum Diselesaikan',
    admin_tab_listings: 'Senarai Hartanah',
    admin_tab_users: 'Pengurusan Pengguna',
    admin_tab_feedback: 'Maklum Balas Pengguna',
    admin_table_property: 'Hartanah',
    admin_table_location: 'Lokasi',
    admin_table_type: 'Jenis',
    admin_table_rent: 'Sewa',
    admin_table_actions: 'Tindakan',
    admin_table_status: 'Status',
    admin_table_reason: 'Sebab Penolakan',
    admin_table_name: 'Nama',
    admin_table_email: 'E-mel',
    admin_table_role: 'Peranan',
    admin_all_listings: 'Semua Senarai',
    admin_all_users: 'Semua Pengguna',
    admin_caught_up: 'Semua selesai! Tiada kelulusan tertunggak.',
    admin_no_feedback: 'Tiada maklum balas dihantar lagi.',
    admin_action_approve: 'Luluskan',
    admin_action_reject: 'Tolak',
    admin_action_resolve: 'Tanda Selesai',

    /* ── About Page ── */
    about_title: 'Tentang RakanSewa',
    about_subtitle: 'Platform khusus membantu pelajar UiTM Jasin mencari perumahan dan rakan serumah yang serasi.',
    about_proj_info: 'Maklumat Projek',
    about_proj_name: 'Nama Projek',
    about_proj_name_val: 'RakanSewa: Sistem Pencari Maklumat Rumah Sewa dan Padanan Rakan Serumah',
    about_dev: 'Pembangun',
    about_univ: 'Universiti',
    about_univ_val: 'Universiti Teknologi MARA (UiTM) Cawangan Melaka, Kampus Jasin',
    about_platform: 'Platform',
    about_platform_val: 'Sistem Berasaskan Web (React + Spring Boot)',
    about_prob_sol: 'Masalah & Penyelesaian',
    about_prob_title: 'Masalah',
    about_prob_desc: 'Mencari penginapan luar kampus yang selamat dan rakan serumah yang serasi sering menjadi proses yang tertekan untuk pelajar universiti. Ramai menghadapi isu seperti senarai tidak disahkan, penipuan tuan rumah, dan rakan serumah yang tidak sepadan dengan gaya hidup yang bercanggah.',
    about_sol_title: 'Penyelesaian',
    about_sol_desc: 'RakanSewa menyediakan platform terpusat dan selamat yang direka secara eksklusif untuk pelajar UiTM. Ia menangani cabaran ini melalui pengesahan tuan rumah, lencana kepercayaan identiti pelajar, dan sistem keserasian rakan serumah pintar berdasarkan bajet dan keutamaan gaya hidup.',
    about_key_features: 'Ciri-Ciri Utama',
    about_feat_verification: 'Pengesahan Pelajar UiTM',
    about_feat_listing: 'Penyenaraian & Kelulusan Hartanah',
    about_feat_matching: 'Sistem Padanan Rakan Serumah',
    about_feat_admin: 'Alur Kerja Kelulusan Pentadbir',
    about_feat_feedback: 'Sistem Maklum Balas Pengguna',
    about_tech_stack: 'Timbunan Teknologi',
    about_academic_proj: 'Projek Akademik',
    about_academic_desc: 'Sistem ini dibangunkan sebagai sebahagian daripada projek tahun akhir sarjana muda di UiTM Cawangan Melaka, Kampus Jasin.',

    /* ── Login Page ── */
    login_welcome: 'Selamat kembali',
    login_sub: 'Log masuk ke akaun RakanSewa anda.',
    login_email: 'E-mel',
    login_email_placeholder: 'e-mel@anda.com',
    login_password: 'Kata Laluan',
    login_forgot_password: 'Lupa kata laluan?',
    login_password_placeholder: 'Masukkan kata laluan anda',
    login_btn_signin: 'Log Masuk',
    login_btn_signing_in: 'Log masuk…',
    login_or: 'atau',
    login_google: 'Teruskan dengan Google',
    login_no_account: 'Tiada akaun?',
    login_register_free: 'Daftar percuma →',
    login_uitm_platform: 'Platform UiTM Jasin',
    login_hero_title: 'Cari rumah sempurna anda',
    login_hero_subtitle: 'dan rakan serumah serasi.',
    login_hero_desc: 'Platform dipercayai untuk pelajar UiTM Jasin mencari senarai sewaan disahkan dan rakan sebilik yang serasi.',
    login_feat_listings: 'Senarai disahkan pelajar UiTM',
    login_feat_matching: 'Skor keserasian rakan serumah pintar',
    login_feat_location: 'Hartanah berhampiran kampus UiTM Jasin',
    login_hero_footer: 'Percuma untuk semua pelajar UiTM Jasin & tuan rumah yang disahkan.',
    login_success_registered: 'Pendaftaran berjaya! Log masuk dan lengkapkan pengesahan pelajar UiTM anda dalam profil anda.',
    login_error_invalid: 'E-mel atau kata laluan tidak sah. Sila cuba lagi.',
    login_error_google: 'Gagal log masuk dengan Google. Sila cuba lagi.',
    login_error_google_failed: 'Log Masuk Google gagal. Sila cuba lagi.',
    login_hide_pwd: 'Sembunyikan kata laluan',
    login_show_pwd: 'Tunjukkan kata laluan',

    /* ── Register Page ── */
    reg_title: 'Daftar akaun anda',
    reg_sub: 'Sertai RakanSewa dan mula mencari tempat sempurna anda.',
    reg_fullname: 'Nama Penuh',
    reg_fullname_placeholder: 'Masukkan nama penuh anda',
    reg_email: 'E-mel',
    reg_email_placeholder: 'e-mel@anda.com',
    reg_email_detected: 'E-mel pelajar UiTM dikesan — pengesahan automatik akan digunakan!',
    reg_password: 'Kata Laluan',
    reg_password_placeholder: 'Cipta kata laluan yang kuat',
    reg_iam: 'Saya seorang…',
    reg_role_student: 'Pelajar UiTM',
    reg_role_owner: 'Pemilik Hartanah',
    reg_verification_title: 'Pengesahan Pelajar UiTM',
    reg_matric: 'Nombor Matrik',
    reg_matric_placeholder: 'cth. 2022456146',
    reg_uitm_email: 'E-mel Pelajar UiTM',
    reg_uitm_email_placeholder: '2022456146@student.uitm.edu.my',
    reg_warning_mismatch: 'Nombor matrik mestilah sepadan dengan e-mel pelajar UiTM anda.',
    reg_warning_match: 'Nombor matrik sepadan dengan e-mel UiTM — pengesahan automatik akan digunakan!',
    reg_btn_create: 'Daftar Akaun',
    reg_btn_creating: 'Mendaftarkan Akaun…',
    reg_free_account: 'Akaun Pelajar Percuma',
    reg_hero_title: 'Sertai UiTM Jasin',
    reg_hero_subtitle: 'komuniti pelajar.',
    reg_hero_desc: 'Daftar akaun percuma anda hari ini. Semak senarai disahkan, cari rakan serumah serasi, dan amankan rumah ideal berhampiran kampus.',
    reg_feat_listings: 'Semak senarai hartanah disahkan',
    reg_feat_matching: 'Padan dengan rakan serumah serasi',
    reg_feat_safety: 'Komuniti selamat, hanya untuk pelajar',
    reg_already_have_account: 'Sudah mempunyai akaun?',
    reg_signin_link: 'Log masuk di sini',

    /* ── ForgotPassword Page ── */
    forgot_left_title_1: 'Recover your account',
    forgot_left_title_2: 'secara selamat.',
    forgot_left_desc: 'Masukkan alamat e-mel berkaitan akaun RakanSewa anda. Kami akan menghantar pautan selamat untuk menetapkan semula kata laluan.',
    forgot_left_priority: 'Keselamatan akaun anda adalah keutamaan kami. Pautan tetapan semula tamat tempoh selepas 30 minit.',
    forgot_title: 'Lupa Kata Laluan',
    forgot_sub: 'Masukkan e-mel anda dan kami akan hantar pautan tetapan semula.',
    forgot_success: 'Sekiranya akaun dengan e-mel tersebut wujud, pautan tetapan semula kata laluan telah dihantar. Sila semak peti masuk anda (dan folder spam).',
    forgot_back: 'Kembali ke Log Masuk',
    forgot_email: 'Alamat E-mel',
    forgot_email_placeholder: 'Masukkan e-mel berdaftar anda',
    forgot_sending: 'Menyimpan...', // or Menghantar... matching forgot_sending
    forgot_send_btn: 'Hantar Pautan Tetapan Semula',
    forgot_remember: 'Ingat kata laluan anda?',
    forgot_signin_link: 'Log masuk',

    /* ── ResetPassword Page ── */
    reset_left_title_1: 'Tetapkan kata laluan baru',
    reset_left_title_2: 'untuk akaun anda.',
    reset_left_desc: 'Pilih kata laluan kuat untuk memastikan akaun RakanSewa anda selamat. Kata laluan anda mestilah sekurang-kurangnya 6 aksara.',
    reset_left_priority: 'Gunakan kata laluan unik yang tidak digunakan di laman web lain.',
    reset_invalid_title: 'Pautan Tetapan Semula Tidak Sah',
    reset_invalid_desc: 'Pautan tetapan semula kata laluan ini hilang atau tidak sah. Sila minta pautan baru.',
    reset_request_new: 'Minta Pautan Baru',
    reset_title: 'Tetapkan Semula Kata Laluan',
    reset_sub: 'Masukkan kata laluan baru anda di bawah.',
    reset_success: 'Kata laluan anda telah berjaya ditetapkan semula!',
    reset_new_label: 'Kata Laluan Baru',
    reset_confirm_label: 'Sahkan Kata Laluan',
    reset_new_placeholder: 'Sekurang-kurangnya 6 aksara',
    reset_confirm_placeholder: 'Masukkan semula kata laluan anda',
    reset_mismatch: 'Kata laluan tidak sepadan.',
    reset_match: 'Kata laluan sepadan.',
    reset_btn: 'Tetapkan Semula Kata Laluan',
    reset_btn_resetting: 'Menetapkan semula...',
    reset_back: 'Kembali ke Log Masuk',
    reset_error_len: 'Kata laluan mestilah sekurang-kurangnya 6 aksara.',

    /* ── Feedback Page ── */
    fb_not_logged_title: 'Sila Log Masuk',
    fb_not_logged_desc: 'Anda mesti log masuk untuk menghantar maklum balas.',
    fb_not_logged_btn: 'Log Masuk',
    fb_title: 'Hantar Maklum Balas',
    fb_guide_title: 'Panduan Maklum Balas',
    fb_subtitle: 'Bantu kami menambah baik RakanSewa dengan berkongsi pendapat, cadangan, atau laporan anda.',
    fb_why_title: 'Mengapa Maklum Balas Penting',
    fb_why_desc: 'Maklum balas anda membentuk perkembangan RakanSewa secara langsung. Setiap cadangan dan laporan disemak oleh pasukan pentadbir dan dipertimbangkan untuk penambahbaikan masa depan.',
    fb_categories_title: 'Kategori Maklum Balas',
    fb_cat_comment: 'Komen',
    fb_cat_comment_desc: 'Pendapat am atau pemerhatian tentang platform.',
    fb_cat_suggestion: 'Cadangan',
    fb_cat_suggestion_desc: 'Idea untuk ciri baru atau penambahbaikan.',
    fb_cat_report: 'Laporan',
    fb_cat_report_desc: 'Laporkan pepijat, isu, atau pelanggaran polisi.',
    fb_logged_in_as: 'Log masuk sebagai',
    fb_form_title: 'Maklum Balas Anda',
    fb_success: 'Terima kasih! Maklum balas anda telah berjaya dihantar.',
    fb_error: 'Gagal menghantar maklum balas. Sila cuba lagi.',
    fb_label_category: 'Kategori',
    fb_label_subject: 'Subjek',
    fb_placeholder_subject: 'Ringkasan ringkas maklum balas anda',
    fb_label_message: 'Mesej',
    fb_placeholder_message: 'Taip mesej maklum balas anda di sini...',
    fb_btn_submit: 'Hantar Maklum Balas',
    fb_btn_submitting: 'Menhantar...',
    fb_ready_title: 'Sedia Kongsi Maklum Balas?',
    fb_ready_desc: 'Bantu pelajar lain dengan berkongsi ulasan rumah dan pengalaman anda di RakanSewa.',
    fb_btn_write: 'Tulis Maklum Balas',
    fb_community_title: 'Maklum Balas Komuniti',
    fb_stat_total: 'Jumlah Maklum Balas',
    fb_stat_comments: 'Komen',
    fb_stat_suggestions: 'Cadangan',
    fb_stat_reports: 'Laporan',
    fb_filter_all: 'Semua Maklum Balas',
    fb_no_feedback: 'Tiada maklum balas ditemui untuk kategori ini.',
    fb_history_title: 'Sejarah Maklum Balas Saya',
    fb_no_history: 'Anda belum menghantar sebarang maklum balas lagi.',
    fb_tbl_category: 'Kategori',
    fb_tbl_subject: 'Subjek',
    fb_tbl_date: 'Tarikh',
    fb_tbl_status: 'Status',
    fb_status_pending: 'Belum Selesai',
    fb_status_reviewed: 'Disemak',
    fb_status_implemented: 'Dilaksanakan',
    fb_anon_student: 'Pelajar Tanpa Nama',
    fb_btn_cancel: 'Batal',
    fb_btn_done: 'Selesai',

    /* ── Profile Page ── */
    profile_google_success: 'Akaun Google berjaya dicipta!',
    profile_google_success_sub: 'Sila lengkapkan profil anda — tambah nombor telefon, nombor matrik, dan pilihan gaya hidup anda.',
    profile_not_verified: 'Tidak Disahkan — Lengkapkan Pengesahan Pelajar UiTM',
    profile_not_verified_sub: 'Nombor matrik anda mestilah sepadan dengan e-mel pelajar UiTM anda, cth. 2022456146@student.uitm.edu.my.',
    profile_not_verified_hint: 'Isi nombor matrik dan e-mel UiTM dalam profil anda untuk disahkan secara automatik.',
    profile_saved: 'Profil berjaya disimpan!',
    profile_role_housemate: 'Rakan Serumah',
    profile_role_verified_student: 'Pelajar Terverifikasi',
    profile_role_not_verified: 'Belum Disahkan',
    profile_acc_info: 'Maklumat Akaun',
    profile_btn_edit: 'Edit Profil',
    profile_btn_cancel: 'Batal',
    profile_btn_save: 'Simpan Perubahan',
    profile_btn_saving: 'Menyimpan...',
    profile_label_fullname: 'Nama Penuh',
    profile_label_email: 'Alamat E-mel',
    profile_label_phone: 'Nombor Telefon',
    profile_label_phone_placeholder: 'cth. 0123456789',
    profile_label_matric: 'Nombor Matrik',
    profile_label_matric_placeholder: 'cth. 2022456146',
    profile_label_uitm_email: 'E-mel UiTM',
    profile_label_uitm_email_placeholder: 'cth. 2022456146@student.uitm.edu.my',
    profile_uitm_email_hint: 'Mesti sepadan dengan nombor matrik anda, cth. 2022456146@student.uitm.edu.my',
    profile_not_provided: 'Tidak disediakan',
    profile_acc_role: 'Peranan Akaun',
    profile_housemate_profile: 'Profil Rakan Serumah',
    profile_btn_manage_housemate: 'Edit Profil Rakan Serumah',
    profile_status_visible: 'Tersenarai & Kelihatan',
    profile_label_budget: 'Bajet Bulanan',
    profile_label_sleep: 'Jadual Tidur',
    profile_label_lifestyles: 'Total Gaya Hidup',
    profile_lifestyles_tags: '{count} tag',
    profile_label_lifestyle_tags_section: 'Tag Gaya Hidup',
    profile_label_priorities_section: 'Keutamaan Padanan',
    profile_not_listed: 'Tidak tersenarai sebagai rakan serumah',
    profile_not_listed_desc: 'Profil anda kini disembunyikan daripada carian rakan serumah.',
    profile_property_summary: 'Ringkasan Hartanah',
    profile_btn_manage_properties: 'Urus Hartanah',
    profile_total: 'Jumlah',
    profile_approved: 'Diluluskan',
    profile_pending: 'Menunggu',
    profile_rejected: 'Ditolak',
    profile_no_listings_yet: 'Tiada sebaran lagi. Pergi ke Urus Hartanah untuk menambah hartanah pertama anda.',
    profile_system_summary: 'Ringkasan Sistem',
    profile_btn_open_admin: 'Buka Papan Pemuka Pentadbir',
    profile_admin_prop_approvals: 'Kelulusan Hartanah',
    profile_admin_prop_approvals_sub: 'Semak senarai menunggu',
    profile_admin_user_mgmt: 'Pengurusan Pengguna',
    profile_admin_user_mgmt_sub: 'Lihat semua pengguna berdaftar',
    profile_admin_feedback: 'Maklum Balas Pengguna',
    profile_admin_feedback_sub: 'Urus laporan & cadangan',
    profile_admin_total_users: 'Jumlah Pengguna',
    profile_admin_students: 'Pelajar',
    profile_admin_owners: 'Pemilik',
    profile_admin_total_listings: 'Jumlah Senarai',
    profile_admin_pending_approvals: 'Kelulusan Menunggu',
    profile_admin_processed: 'Diproses',
    profile_linked_property: 'Hartanah Sewa Berkaitan',
    profile_no_property_linked: 'Tiada hartanah berkait buat masa ini',

    /* ── Property Filter Component ── */
    pfilter_search: 'Carian',
    pfilter_search_placeholder: 'Tajuk atau bandar...',
    pfilter_furnishing: 'Perabot',

    /* ── Dynamic options mapping ── */
    'Budget': 'Bajet',
    'Sleep Pattern': 'Corak Tidur',
    'Cleanliness': 'Kebersihan',
    'Quietness': 'Ketenangan',
    'Social Style': 'Gaya Bersosial',
    'Study Habit': 'Tabiat Belajar',
    'Activity Level': 'Tahap Aktiviti',
    'Flexibility': 'Kefleksibelan',
    'Clean': 'Bersih',
    'Quiet': 'Senyap',
    'Social': 'Sosial',
    'Studious': 'Rajin Belajar',
    'Active': 'Aktif',
    'Flexible': 'Fleksibel',
    'Early Bird': 'Burung Awal',
    'Night Owl': 'Burung Hantu',
    'Monthly rent affordability': 'Kemampuan sewa bulanan',
    'Early bird or night owl': 'Corak tidur awal atau malam',
    'Tidiness & hygiene habits': 'Tabiat kekemasan & kebersihan',
    'Noise level preference': 'Keutamaan tahap bunyi',
    'Social or introverted': 'Sosial atau introvert',
    'Study environment needs': 'Keperluan persekitaran belajar',
    'Active lifestyle match': 'Kesesuaian gaya hidup aktif',
    'Adaptability to schedules': 'Kemampuan menyesuaikan jadual',
    'Honest preferences lead to better matches.': 'Keutamaan yang jujur membawa kepada padanan yang lebih baik.',
    'Setting a realistic budget improves compatibility.': 'Bajet yang realistik meningkatkan keserasian.',
    'Sleep schedule is the #1 source of housemate conflict.': 'Jadual tidur adalah punca utama konflik rakan sebilik.',
    'More lifestyle tags = more precise matching.': 'Lebih banyak tag gaya hidup = padanan yang lebih tepat.',
    'Linked property helps others find you faster.': 'Hartanah berkaitan membantu orang lain menemui anda dengan lebih cepat.',
    'Apartment': 'Pangsapuri',
    'Terrace': 'Teres',
    'Condo': 'Kondominium',
    'Single': 'Single',
    'Master': 'Bilik Utama',
    'Middle': 'Bilik Tengah',
    'Fully Furnished': 'Perabot Penuh',
    'Partially Furnished': 'Sebahagian Perabot',
    'Unfurnished': 'Tiada Perabot',
    'Melaka': 'Melaka',
    'filter_location': 'Lokasi',
    'filter_all_locations': 'Semua Lokasi',
    'filter_all_types': 'Semua Jenis',
    unsaved_title: 'Perubahan Belum Disimpan',
    unsaved_msg: 'Anda mempunyai perubahan yang belum disimpan. Adakah anda mahu menyimpan sebelum keluar?',
    unsaved_save: 'Simpan Perubahan',
    unsaved_discard: 'Abaikan',
    unsaved_cancel: 'Batal',
    val_err_required: 'Medan ini diperlukan.',
    val_err_email_invalid: 'Sila masukkan alamat e-mel yang sah.',
    val_err_phone_numeric: 'Nombor telefon mesti mengandungi nombor sahaja.',
    val_err_phone_empty: 'Nombor telefon tidak boleh kosong.',
    val_err_too_long: 'Medan ini melebihi had maksimum {max} aksara.',
    val_err_numeric_positive: 'Mesti nombor positif melebihi 0.',
    val_err_numeric_only: 'Mesti berupa nombor.',
    val_err_select_empty: 'Sila pilih pilihan yang sah.',
    val_err_password_len: 'Kata laluan mestilah sekurang-kurangnya 6 aksara.',
    val_err_max_value: 'Nilai maksimum yang dibenarkan ialah {max}.',
    profile_label_allow_contact: 'Benarkan kongsi maklumat perhubungan',
    profile_label_show_whatsapp: 'Tunjukkan butang WhatsApp',
    profile_allow_contact_hint: 'Jika dibenarkan, pelajar yang dipadankan akan melihat butang untuk menghubungi anda.',
    profile_show_whatsapp_hint: 'Benarkan pemesejan terus melalui pautan WhatsApp.',
    profile_label_contact_settings: 'Tetapan Privasi Perhubungan',
    match_contact_student: 'Hubungi Pelajar',
    match_contact_disabled: 'Hubungan Tidak Dikongsi',
    match_whatsapp_intro: 'Hai! Saya jumpa profil anda di RakanSewa. Boleh kita jadi rakan serumah?',
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('rs-lang') || 'en'; }
    catch { return 'en'; }
  });

  const toggle = useCallback(() => {
    setLang(prev => {
      const next = prev === 'en' ? 'ms' : 'en';
      try { localStorage.setItem('rs-lang', next); } catch { /* ignore */ }
      return next;
    });
  }, []);

  /**
   * Translate a key.
   * Falls back to English, then returns the key itself if not found.
   * Supports {count} interpolation: t('prop_results', { count: 5 })
   */
  const t = useCallback((key, vars) => {
    let str = STRINGS[lang]?.[key] ?? STRINGS['en']?.[key] ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(`{${k}}`, v);
      });
    }
    return str;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
};
